version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
    container_name: store-frontend
    restart: always
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules

  backend:
    build:
      context: ./backend
    container_name: store-backend
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend
      - ./backend/node_modules

  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    container_name: store-nginx
    restart: always
    depends_on:
      - frontend
      - backend
