version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
    container_name: store-frontend
    restart: always
    command: bash -c "npm start"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: store-backend
    restart: always
    command: bash -c "npm run dev"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: store-mongodb
    ports:
      - 27017:27017

  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    container_name: store-nginx
    restart: always
    depends_on:
      - frontend
      - backend
